DATASET:
  name: 'Adobe_Image_Matting'
  data_dir: '/home/yezixuan/Combined_Dataset'
  train_fg_list: 'train_fg.txt'
  train_alpha_list: 'train_alpha.txt'
  train_bg_list: 'train_bg.txt'
  val_list: 'test.txt'
  composition_style: 'tri'



TRAIN:
  model_save_dir: './savemodel'
  random_seed: 6
  evaluate_only: False
  crop_size: 512
  batch_size: 16
  initial_lr: 0.01
  num_epochs: 30
  epoch_iterations: 6000
  num_workers: 8
  freeze_bn: True
  apex: False
  load_data: False
  load_bg: False
  lmdb: False
  random_bgidx: True
  all_bg: True




EXP: 'composition styles'
